trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - script: npm install
    displayName: 'install dependencies'

  - script: quasar build
    displayName: 'build'

  - task: CopyFiles@2
    inputs:
      SourceFolder: './dist/spa'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'my-project'
      publishLocation: 'Container'